### PR TITLE
do not allocate a new offset buffer if the slice starts at 0 since th…

### PR DESCRIPTION
**Pull request by scampi**
…e relative offset pointer would be unchanged

### CODE REVIEW

**Review by GeorgeAp — APPROVED** [review]

**Comment by rendel** [comment]
Is there a way to reproduce that in a test

**Comment by scampi** [comment]
> Is there a way to reproduce that in a test

@rendel Is this something that @GeorgeAp could do ? I think this way he gets knowledge about that tricky arrow lib.

**Comment by rendel** [comment]
I meant on the federate project to reproduce the memory leak, 
but maybe it is too complicated to do

**Comment by scampi** [comment]
ah sorry. I can to reproduce it there on the federate project.

**Comment by scampi** [comment]
@rendel I cannot manage to create a unit test that reproduce the memory leak I was seeing.
There is a test for the borrow, but as I extended it with a binary field, I wasn't getting any leak. Therefore, this shows there is an error in our cleanup logic upon exception.

https://github.com/sirensolutions/siren-platform/blob/a213418745c75e963362cc7b943f1218b0b62e45/core/src/test/java/io/siren/federate/core/network/DataTransferActionTest.java#L79-L90

**Pull request merged**
